Models/CompactDisc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace EF_lab.Models
{
    public class CompactDisc
    {
        public int CompactDiscId { get; set; }
        
        [DisplayName("Title")]
        public string CompactDiscTitle { get; set; }
        
        [DisplayName("Artist")]
        public string ArtistName { get; set; }
        
        [DisplayName("Genre")]
        public int GenreId { get; set; }
        public Genre Genre { get; set; }
    }
}

Models/CompactDiscContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EF_lab.Models
{
    public class CompactDiscContext:DbContext
    {
        public CompactDiscContext(DbContextOptions<CompactDiscContext> options) : base(options)
        {

        }

        public DbSet<CompactDisc> Discs { get; set; }
        public DbSet<Genre> Genres { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace EF_lab.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EF_lab.Models
{
    public class Genre
    {
        public int GenreId { get; set; }
        public string GenreName { get; set; }
        public List<CompactDisc> CompactDiscs { get; set; }
    }
}

Controllers/CompactDiscsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EF_lab.Models;

namespace EF_lab.Controllers
{
    public class CompactDiscsController : Controller
    {
        private readonly CompactDiscContext _context;

        public CompactDiscsController(CompactDiscContext context)
        {
            _context = context;
        }

        // GET: CompactDiscs
        public async Task<IActionResult> Index()
        {
            var compactDiscContext = _context.Discs.Include(c => c.Genre);
            return View(await compactDiscContext.ToListAsync());
        }

        // GET: CompactDiscs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compactDisc = await _context.Discs
                .Include(c => c.Genre)
                .FirstOrDefaultAsync(m => m.CompactDiscId == id);
            if (compactDisc == null)
            {
                return NotFound();
            }

            return View(compactDisc);
        }

        // GET: CompactDiscs/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName");
            return View();
        }

        // POST: CompactDiscs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompactDiscId,CompactDiscTitle,ArtistName,GenreId")] CompactDisc compactDisc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compactDisc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName", compactDisc.GenreId);
            return View(compactDisc);
        }

        // GET: CompactDiscs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compactDisc = await _context.Discs.FindAsync(id);
            if (compactDisc == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName", compactDisc.GenreId);
            return View(compactDisc);
        }

        // POST: CompactDiscs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompactDiscId,CompactDiscTitle,ArtistName,GenreId")] CompactDisc compactDisc)
        {
            if (id != compactDisc.CompactDiscId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compactDisc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompactDiscExists(compactDisc.CompactDiscId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "GenreId", "GenreName", compactDisc.GenreId);
            return View(compactDisc);
        }

        // GET: CompactDiscs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compactDisc = await _context.Discs
                .Include(c => c.Genre)
                .FirstOrDefaultAsync(m => m.CompactDiscId == id);
            if (compactDisc == null)
            {
                return NotFound();
            }

            return View(compactDisc);
        }

        // POST: CompactDiscs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compactDisc = await _context.Discs.FindAsync(id);
            _context.Discs.Remove(compactDisc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompactDiscExists(int id)
        {
            return _context.Discs.Any(e => e.CompactDiscId == id);
        }
    }
}

Views/CompactDiscs/Create.cshtml
@model EF_lab.Models.CompactDisc

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompactDisc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompactDiscTitle" class="control-label"></label>
                <input asp-for="CompactDiscTitle" class="form-control" />
                <span asp-validation-for="CompactDiscTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistName" class="control-label"></label>
                <input asp-for="ArtistName" class="form-control" />
                <span asp-validation-for="ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class ="form-control" asp-items="ViewBag.GenreId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompactDiscs/Delete.cshtml
@model EF_lab.Models.CompactDisc

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompactDisc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompactDiscTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompactDiscTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtistName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompactDiscId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/CompactDiscs/Details.cshtml
@model EF_lab.Models.CompactDisc

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CompactDisc</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CompactDiscTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CompactDiscTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtistName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtistName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CompactDiscId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/CompactDiscs/Edit.cshtml
@model EF_lab.Models.CompactDisc

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CompactDisc</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompactDiscId" />
            <div class="form-group">
                <label asp-for="CompactDiscTitle" class="control-label"></label>
                <input asp-for="CompactDiscTitle" class="form-control" />
                <span asp-validation-for="CompactDiscTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistName" class="control-label"></label>
                <input asp-for="ArtistName" class="form-control" />
                <span asp-validation-for="ArtistName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompactDiscs/Index.cshtml
@model IEnumerable<EF_lab.Models.CompactDisc>

@{
    ViewData["Title"] = "My CD's";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompactDiscTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtistName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompactDiscTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtistName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.GenreName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CompactDiscId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CompactDiscId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CompactDiscId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EF_lab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CompactDiscs" asp-action="Index">EF_lab</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompactDiscs" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EF_lab
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>